### ISSUE TITLE
Wordpress workflow: error "kCFErrorDomainCFNetwork"

### ISSUE THREAD

**Issue by usizu** [sbusso/Bear-Power-Pack#2]
In the past this workflow has worked for me, but I changed the wordpress credentials and it no longer works with the new ones. I've tried deleting it and re-installing the shortcut.

I can't seem to add the wordpress user credentials in to the workflow. After putting in the login credentials and tapping Log In, I get the following error:

`The operation couldn't be completed. (kCFErrorDomainCFNetwork error 303.)`

Any tips as to what this error means?

**Comment by sbusso** [comment]
From Google it seems to be linked to an encoding issue
