### ISSUE TITLE
Add BearSync

### ISSUE THREAD

**Issue by d4rkd3v1l** [sbusso/Bear-Power-Pack#6]
Hey there,

really like your collection of workflows/tools. It kinda inspired me to write [BearSync](https://github.com/d4rkd3v1l/BearSync), a little macOS App to synchronize some notes between different accounts. 
I would really love to see it incorporated into this collection here :-)

**Comment by sbusso** [comment]
@d4rkd3v1l BearSync was added to the list, thanks for the mention
